#!/usr/bin/env bash
version="v0.1"

idle_write(){
    if [[ -f "/tmp/idletime" ]]; then
        rm  "/tmp/idletime";
    fi
    "xprintidle" >> "/tmp/idletime";        #idle time in miliseconds
    idle=$(head -1 /tmp/idletime);          #set $idle as time
}

idle_check(){
    idle_write
    echo $idle
    if [[ $idle -gt 10 ]]; then             #if idle is greater than x(#)
        timeout=true;
        echo "its over";
    else
        timeout=false;
        echo "its under";
    fi
}

user_prompt(){
    shutdown -h +1;                         #shutdown and halt in 1 minute
    echo "please enter the password or the machine with shutdown"
    sudo true;
    if [[ $? = 0 ]]; then                   #passed
        auth=true;
        echo "you passed!";
    else                                    #failed
        auth=false;
        echo "you failed!";
    fi
}

main() {
    idle_check
    if [[ $timeout==true ]]; then
        user_prompt
        if [[ $auth==false ]]; then
            shutdown -c;
            shutdown -h;
        else
            shutdown -c;
            exit;
        fi
    fi
}

case "$1" in
    *)
        main
        ;;
esac
